

-- TODO: perform a check when starting to check if the files from database are there 




CREATE TABLE IF NOT EXISTS TOPIC (

    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    TITLE TEXT,

);




CREATE TABLE IF NOT EXISTS FILE (

    ID INTEGER PRIMARY KEY AUTOINCREMENT,

    TOPIC INTEGER,

    TITLE TEXT,

    TYPE TEXT,

    -- NUMBER_WORDS INTEGER,

    LAST_UPDATE TEXT,

    FOREIGN KEY (TOPIC) REFERENCES TOPIC( ID)

);


INSERT INTO TOPIC ( TITLE) VALUES ( 'TOPIC1');
INSERT INTO TOPIC ( TITLE) VALUES ( 'TOPIC2');
INSERT INTO TOPIC ( TITLE) VALUES ( 'TOPIC3');

INSERT INTO FILE ( TOPIC, TITLE, TYPE, LAST_UPDATE) VALUES ( 1, 'FILE1', 'pdf', DATETIME('2024-12-25 19:00:00'));
INSERT INTO FILE ( TOPIC, TITLE, TYPE, LAST_UPDATE) VALUES ( 2, 'FILE1', 'pdf', DATETIME('2024-12-25 19:00:00'));
INSERT INTO FILE ( TOPIC, TITLE, TYPE, LAST_UPDATE) VALUES ( 3, 'FILE1', 'pdf', DATETIME('2024-12-25 19:00:00'));


