// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:number,arg4:string):Promise<database.Task>;

export function GetTasks():Promise<Array<database.Task>>;

export function RemoveTask(arg1:number):Promise<void>;

export function UpdateTaskList(arg1:number,arg2:string):Promise<void>;
