// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:number,arg4:string):Promise<database.Task>;

export function GetActivities(arg1:number):Promise<Array<database.Activity>>;

export function GetDaysStatistics(arg1:number):Promise<Array<database.DayStatistics>>;

export function GetHistory():Promise<Array<database.HistoryDay>>;

export function GetStatistics():Promise<database.Statistics>;

export function GetTasks():Promise<Array<database.Task>>;

export function GetWeekStatistics(arg1:number):Promise<database.WeekStatistic>;

export function RemoveTask(arg1:number):Promise<void>;

export function UpdateTaskList(arg1:number,arg2:string):Promise<void>;
